### PR TITLE
Addition of PassThrough for array upload

### PR DESCRIPTION
**Pull request by dimitrius1986**

### CODE REVIEW

**Comment by ikhsanalatsary** [comment]
hi @dimitrius1986 why you close this?

**Comment by dimitrius1986** [comment]
I thought it solved it but it just writes the last file to all the files, don't know why... Is it because of observables

**Comment by dimitrius1986** [comment]
I changed sizes from observable to array (const sizes = opts.resize) and just doing        sizes.map((size) => {}, it works for me since i don't really care what it returns not sure if that is a good way to go since it should probably return one object instead of number of sizes results. not really know enough about observables, is there a way to attach stream to the size observable ?

**Comment by ikhsanalatsary** [comment]
I think, we need passthrough the stream
```
 const streamCopy = new PassThrough()
 stream.pipe(streamCopy)
 const resizerStream = transformer(sharpOpts, size)
 if (size.suffix === 'original') {
   size.Body = streamCopy.pipe(sharp())
 } else {
    size.Body = streamCopy.pipe(resizerStream)
 }
 return size
```

ref:   https://github.com/ikhsanalatsary/multer-sharp-s3/blob/b1a9e096393d7a0f1ec1222c716f7d275bac1df3/src/main.ts#L122

**Comment by dimitrius1986** [comment]
I tried it but it still gets the stream of the final file, the size observable is not running as soon as stream comes in but schedules it i think, and when it does run it get the stream of the final file. thats what i noticed

**Comment by dimitrius1986** [comment]
https://github.com/dimitrius1986/multer-sharp-s3/blob/master/src/main.ts this works but the return has the last size key only

**Comment by ikhsanalatsary** [comment]
I know the problem. The stream doesn't stop when something error in sharp readable stream and still continue the process to the writable stream S3. So why the result uploaded 0 byte.

**Pull request closed without merging**
